version: '3.9'
services:
  pyd-api.mongo:
    image: mongo
    restart: always
    container_name: pyd-api.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017

    volumes:
      - ./mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1.5
